In [1]:
using DelimitedFiles, Statistics, Random
Random.seed!(1);

EXERCISE 1

In [14]:
@doc readdlm;
download("https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data","housing.data.txt")
input=readdlm("housing.data.txt", Float64)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49082  100 49082    0     0  81367      0 --:--:-- --:--:-- --:--:-- 81261


506×14 Array{Float64,2}:
 0.00632  18.0   2.31  0.0  0.538  6.575  …  296.0  15.3  396.9    4.98  24.0
 0.02731   0.0   7.07  0.0  0.469  6.421     242.0  17.8  396.9    9.14  21.6
 0.02729   0.0   7.07  0.0  0.469  7.185     242.0  17.8  392.83   4.03  34.7
 0.03237   0.0   2.18  0.0  0.458  6.998     222.0  18.7  394.63   2.94  33.4
 0.06905   0.0   2.18  0.0  0.458  7.147     222.0  18.7  396.9    5.33  36.2
 0.02985   0.0   2.18  0.0  0.458  6.43   …  222.0  18.7  394.12   5.21  28.7
 0.08829  12.5   7.87  0.0  0.524  6.012     311.0  15.2  395.6   12.43  22.9
 0.14455  12.5   7.87  0.0  0.524  6.172     311.0  15.2  396.9   19.15  27.1
 0.21124  12.5   7.87  0.0  0.524  5.631     311.0  15.2  386.63  29.93  16.5
 0.17004  12.5   7.87  0.0  0.524  6.004     311.0  15.2  386.71  17.1   18.9
 0.22489  12.5   7.87  0.0  0.524  6.377  …  311.0  15.2  392.52  20.45  15.0
 0.11747  12.5   7.87  0.0  0.524  6.009     311.0  15.2  396.9   13.27  18.9
 0.09378  12.5   7.87  0.0  0.524  5.88

EXERCISE 2

In [15]:
y=reshape(input[:,14],(1,506))

1×506 Array{Float64,2}:
 24.0  21.6  34.7  33.4  36.2  28.7  …  16.8  22.4  20.6  23.9  22.0  11.9

EXERCISE 3

In [16]:
newmatrix=transpose(((input.-mean(input,dims=1))./std(input,dims=1))[:,1:13])

13×506 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
 -0.419367  -0.416927  -0.416929  …  -0.413038  -0.407361  -0.41459 
  0.284548  -0.48724   -0.48724      -0.48724   -0.48724   -0.48724 
 -1.28664   -0.592794  -0.592794      0.115624   0.115624   0.115624
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329
 -0.144075  -0.73953   -0.73953       0.157968   0.157968   0.157968
  0.413263   0.194082   1.28145   …   0.983986   0.724955  -0.362408
 -0.119895   0.366803  -0.265549      0.796661   0.736268   0.434302
  0.140075   0.556609   0.556609     -0.772919  -0.667776  -0.61264 
 -0.981871  -0.867024  -0.867024     -0.981871  -0.981871  -0.981871
 -0.665949  -0.986353  -0.986353     -0.802418  -0.802418  -0.802418
 -1.45756   -0.302794  -0.302794  …   1.1753     1.1753     1.1753  
  0.440616   0.440616   0.396035      0.440616   0.402826   0.440616
 -1.0745    -0.491953  -1.20753      -0.982076  -0.864446  -0.668397

EXERCISE 4

In [17]:
ids=randperm(506);

In [18]:
traIndices=ids[1:400]
xtra=newmatrix[:,traIndices]
ytra=y[:,traIndices]

1×400 Array{Float64,2}:
 26.4  16.1  17.1  19.0  21.7  17.4  …  23.9  18.3  8.8  18.6  19.8  22.8

In [19]:
testIndices=ids[401:506]
xtest=newmatrix[:,testIndices]
ytest=y[:,testIndices]

1×106 Array{Float64,2}:
 20.3  27.5  22.0  30.7  19.4  24.5  …  24.8  42.3  16.3  19.1  20.3  29.8

EXERCISE 5

In [20]:
#Ex 5 
w=randn((1,13)).*0.1

1×13 Array{Float64,2}:
 0.0426637  0.0378471  -0.169487  …  -0.0208622  -0.066244  -0.0257344

EXERCISE 6

In [21]:
function predict(w,x)
    w*x
end
ypredTest=predict(w,xtest)
ypredTrain=predict(w,xtra)

predict (generic function with 1 method)

EXERCISE 7

In [39]:
function MSE(y,ŷ)
    n=length(ŷ)
    j=(.5/n)*(sum(abs2.(y-ŷ) ))
end

MSE (generic function with 1 method)

In [51]:
jTrain=MSE(ytra,ypredTrain)

297.30365032767753

In [52]:
jTest=MSE(ytest,ypredTest)

299.0172855668773

EXERCISE 8

In [49]:
absoluteDiff=(abs.((ypredTrain-ytra)))
jSqrt=sqrt.(jTrain)
count(sqrt.(jTrain).>absoluteDiff)

108